tokens = {
    "y":"Y",
"clase":"CLASE",
"ademas":"ADEMAS",
"falso":"FALSO",
"para":"PARA",
"fun":"FUN",
"si":"SI",
"nulo":"NULO",
"o":"O",
"imprimir":"IMPRIMIR",
"retornar":"RETORNAR",
"super":"SUPER",
"este":"ESTE",
"verdadero":"VERDADERO",
"var":"VAR",
"mientras":"MIENTRAS",
"identificador":"IDENTIFICADOR",
"cadena":"CADENA",
"numero":"NUMERO",
"(":"PAR ABRE",
")":"PAR CIERRA",
"{":"LLAVE ABRE",
"}":"LLAVE CIERRA",
",":"COMA",
".":"PUNTO",
";":"PUNTOYCOMA",
"-":"MENOS",
"+":"MAS",
"*":"MULT",
"/":"DIVISION",
"!":"NEGACION",
"!=":"NOESIGUAL",
"=":"ASIGNACION",
"==":"IGUAL",
"<":"MENOR",
"<=":"MENOROIGUAL",
">":"MAYOR",
">=":"MAYOROIGUAL",
"//":"COMENTARIO",
"/*":"COMENTARIO",
"*/":"COMENTARIO",
"1":"NUMERO",
"2":"NUMERO",
"3":"NUMERO",
"4":"NUMERO",
"5":"NUMERO",
"6":"NUMERO",
"7":"NUMERO",
"8":"NUMERO",
"9":"NUMERO",
"0":"NUMERO"
       }


